# Generated by Django 3.2.9 on 2021-12-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={},
        ),
        migrations.AddConstraint(
            model_name='activitytype',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_activitytype'),
        ),
    ]
