# Generated by Django 3.2.9 on 2022-03-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
